project:
  type: website

website:
  title: "Vishal Katti"
  navbar:
    search: true
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/vkatti
      - icon: twitter
        href: https://twitter.com/vishal_katti
      - icon: linkedin
        href: https://www.linkedin.com/in/vishalkatti
  page-footer: 
    left: Vishal Katti {{< fa regular copyright >}} 2022<br>made with {{< fa heart >}}, {{< fa brands r-project >}}  and [quarto](https://quarto.org)
    right: 
      - icon: github
        href: https://github.com/vkatti
      - icon: twitter 
        href: https://twitter.com/vishal_katti
  site-url: https://vishalkatti.com
  twitter-card: true
  open-graph: true
format:
  html:
    theme: 
      light: litera
      dark: superhero
    code-link: true
    code-fold: true
    code-tools: 
      toggle: true
      source: false



