project:
  type: website
  preview:
    port: 4200
    browser: true

website:
  title: "Vishal Katti"
  site-url: https://vishalkatti.com
  description: "Vishal Katti's Blog"
  navbar:
    search: true
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/vkatti
      - icon: twitter
        href: https://twitter.com/vishal_katti
      - icon: linkedin
        href: https://www.linkedin.com/in/vishalkatti
      - icon: rss
        file: index.xml
  page-footer: 
    left: Vishal Katti ©️ 2022<br>made with 💖, R and [quarto](https://quarto.org)
    right: 
      - icon: github
        href: https://github.com/vkatti
      - icon: twitter 
        href: https://twitter.com/vishal_katti
  
  twitter-card: 
    site: "@vishal_katti"
  open-graph: true
  comments: 
    utterances:
      repo: vkatti/turbokat
format:
  html:
    theme: 
      light: litera
      dark: superhero
    code-link: true
    code-fold: show
    code-tools: 
      toggle: true
      source: false
    code-line-numbers: true
    toc: true
    highlight-style: arrow
    css: styles.css
    mainfont: Candara



